### ISSUE TITLE
スレッドタイトルの取得が少しおかしい．

### ISSUE THREAD

**Issue by nitoca** [half-blue/A_plus_Tsukuba#11]
例えば，thread_numが100のFirst Year Seminar(モゲス アブ ギルマ)を取得するとFirstだけが取得される
![スクリーンショット 2022-08-21 5 55 51](https://user-images.githubusercontent.com/78777225/185765751-69b59395-5494-4376-b65b-e5b3b7e29a07.png)
．
ゆえに，クッキーのbookmarkキーのvalueオブジェクトの中のスレッドタイトルとdropdownのブックマーク表記がおかしくなってる．

**Comment by takumi1001** [comment]
修正済み、
