### ISSUE TITLE
スマホ版で講義スレッド検索が少しみづらい

### ISSUE THREAD

**Issue by nitoca** [half-blue/A_plus_Tsukuba#14]
![IMG_3666](https://user-images.githubusercontent.com/78777225/185947159-6d2f1a14-a928-40c1-8a8a-a104082f0c6b.PNG)
![IMG_3665](https://user-images.githubusercontent.com/78777225/185947194-ab14dfe7-2498-4231-bf06-f36ad1c3802b.PNG)
多くの講師がいる授業のせいでスマホだとみづらくなる。

**Comment by takumi1001** [comment]
直しました
