### ISSUE TITLE
/serach/の検索システムを書き直す

### ISSUE THREAD

**Issue by takumi1001** [half-blue/A_plus_Tsukuba#19]

**Comment by takumi1001** [comment]
現状の問題
 - `Vue.js`に切り替えると動かない
 - 子コンボ―ネットを使ったよくわからない書き方をしており何をしているのかわかりづらい
 - `v-model`と`v-on`が併用されている

**Comment by takumi1001** [comment]
@takumi1001 が責任をもって書き直す

**Comment by takumi1001** [comment]
かなりシンプルに書き直した。Vue2をVue3にするので精いっぱいだったのであまり読みやすくはなっていないかもしれない。計測はしていないが少し早くなった気がする。

**Comment by takumi1001** [comment]
look PR #24

**Comment by nitoca** [comment]
ローカル環境で動作確認しました。問題ないと思います。
土曜日旅行行く前までにコードを見て詳しいコードレビューします。
