### ISSUE TITLE
ITFchk.js のリファクタリング

### ISSUE THREAD

**Issue by takumi1001** [half-blue/A_plus_Tsukuba#20]
問題点
 - 書いた人(@takumi1001 )にしかロジックがわからなくなっている。
 - 名前空間を汚染している。
 - 汚い。

**Comment by takumi1001** [comment]
@takumi1001 が責任もって書き直します

**Comment by nitoca** [comment]
wiki読みました！コード変更履歴にもコメントしましたが、
こちらでコメントを残すルールなのでもう一度コメントしておきます！

ローカル環境で正しく動作することを確認しました。
コードとても読みやすくなりました！

**Comment by ssf2xguile** [comment]
読みやすくなってるのでマージしてok
