### ISSUE TITLE
aboutページのリファクタリング

### ISSUE THREAD

**Issue by ssf2xguile** [half-blue/A_plus_Tsukuba#21]
#### 現状の問題  
* htmlにスタイスを直書きしている。  
* 保守性が保たれない。  
   
#### 修正方針  
* 極力Bootstrapで解決できそうなstyleはBootstrapのクラスで書き直す  。
* Bootstrapで直せなさそうなstyleはcssにまとめる。

**Comment by takumi1001** [comment]
いい感じだと思います！

好みの問題かもしれないのですが、以前のコードだと、`<br class=sma>`でスマートフォンでのみ改行するようにしていました。(`.sma`は`common.css`で定義されています。)

![image](https://user-images.githubusercontent.com/40143183/189118637-9c5a41ff-58a6-4e40-b3bd-e3ba0c90a65d.png)
![image](https://user-images.githubusercontent.com/40143183/189118975-0a16b760-bb1c-4691-ba61-23ed918d1e1a.png)

この機能がいるか要らないかわからないですが、ありバージョンのcommitを打ってみようと思います。

**Comment by takumi1001** [comment]
mergeされました　#22
