### ISSUE TITLE
学群、学類ごとに雑談スレッドの作成

### ISSUE THREAD

**Issue by nitoca** [half-blue/A_plus_Tsukuba#44]
学群ごと？学類ごと？

**Comment by takumi1001** [comment]
- 雑談ページを作る `/talk/`
   - 雑談ページには、各学群へのスレッドへのリック/ボタン・フィードバッグスレッドへのリンクを置く
 - 雑談ページへのリンクは検索バーのすぐ下に小さくと、A+つくばドキュメントのカードに。

 - スレッド自体は僕が作ってissueに貼る

**Comment by ssf2xguile** [comment]
明日は用あって多分できないから、金曜日やる

**Comment by ssf2xguile** [comment]
田村君ありがとう

**Comment by takumi1001** [comment]
システムメッセージとして簡単な投稿を各スレッドに置いておいた
新規質問のリストに載らないように、管理画面から投稿日時を1970年にして投稿した

どうでもいいが今夜のセブンイレブン松見公園前店うるさすぎる

**Comment by ssf2xguile** [comment]
手作業で追加してくれたスレッドのリンクをもとにボタンを追加した
