### ISSUE TITLE
`ITF.`だとチェックを通過できない

### ISSUE THREAD

**Issue by takumi1001** [half-blue/A_plus_Tsukuba#51]
>https://twitter.com/chikuwa_ITF/status/1576183959859253249
>https://twitter.com/chikuwa_ITF/status/1576174950234619906

<s>そのうち修正して、宣伝の一環として利用できそう</s>

**Comment by nitoca** [comment]
これをやらないとITF.警察がうるさいからね

**Comment by takumi1001** [comment]
deploy完了
