### ISSUE TITLE
ブランチが多すぎる

### ISSUE THREAD

**Issue by takumi1001** [half-blue/A_plus_Tsukuba#80]
と，思った．

不要なもの（古いもの・マージ済みのもの）は消したい．

**Comment by nitoca** [comment]
そうだね...

**Comment by takumi1001** [comment]
削除ルール案
・マージされたものは即削除（GitHub Flowおける推奨）
・マージされていないものでも、3カ月以上たったものは削除する

**Comment by takumi1001** [comment]
掃除完了。
各位、いらないものは自分で消すようにしてください。
